#pragma config(Sensor, port4,    gyroscope,      sensorVexIQ_Gyro)
#pragma config(Sensor, port7,    distanceSensor, sensorVexIQ_Distance)
#pragma config(Sensor, port8,    clawBumper,     sensorVexIQ_Touch)
#pragma config(Sensor, port9,    frontBumper,    sensorVexIQ_Touch)
#pragma config(Motor,  motor1,   rightMotor,     tmotorVexIQ, openLoop,   reversed, encoder)
#pragma config(Motor,  motor6,   leftMotor,      tmotorVexIQ, openLoop,   encoder)
#pragma config(Motor,  motor10,  armMotor,       tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,  clawMotor,      tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
Move forward until the VEX IQ Distance Sensors sees an object 100 millimeters (mm) away. The VEX
IQ Distance Sensor returns values in millimeters.

ROBOT CONFIGURATION: VEX IQ Clawbot
MOTORS & SENSORS:
[I/O Port]          [Name]              [Type]                  [Info]
Port 7              distanceSensor      VEX IQ Distance         Distance Sensor (returns mm)
Port 1              rightMotor          VEX IQ Motor            Left side motor (reversed)
Port 6              leftMotor           VEX IQ Motor            Right side motor
------------------------------------------------------------------------------------------------*/
#include "claw.h"

task main()
{
    resetArmPosition();
    setArmPosition(45);
    sleep(2000);
    setArmPosition(180);
    sleep(2000);
    setArmPosition(90);
    sleep(2000);
    resetArmPosition();
}
